openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/agraignic/EcobenchmarkBackEnd/0.0.1
info:
  description: An API template to compare the energy consumption of several languages API backend.
  version: "0.0.1"
  title: Boavizta - Eco benchmark template API
  contact:
    name: 'Boavizta'
    url: https://boavizta.org/
  license:
    name: GNU Affero General Public License v3.0
    url: 'https://www.gnu.org/licenses/agpl-3.0.en.html'
tags:
  - name: developers
    description: Operations available to regular developers
paths:
  /api/accounts:
    post:
      summary: Create an account
      operationId: createAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
  /api/accounts/{accountId}/lists:
    get:
      summary: Get task lists of an account
      operationId: getListsFromAccount
      parameters:
        - in: path
          name: accountId
          schema:
            type: string
          required: true
          description: UUID of the account who own the task lists
      responses:
        '200':
          description: A list of accounts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '404':
          description: An account with the specified ID was not found.
    post:
      summary: Create a task list for a given account
      operationId: createList
      parameters:
        - in: path
          name: accountId
          schema:
            type: string
          required: true
          description: UUID of the account who own the task lists
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/List'
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/List'
        '404':
          description: An account with the specified ID was not found.
  /api/lists/{listId}/tasks:
    post:
      summary: Create a task in a given list
      operationId: createTask
      parameters:
        - in: path
          name: listId
          schema:
            type: string
          required: true
          description: UUID of the task list
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: An list with the specified ID was not found.
  /api/stats:
    get:
      tags:
        - developers
      summary: Get statistics about all accounts, their lists and tasks.
      operationId: stats
      responses:
        '200':
          description: A list of accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExtendedAccount'
                  
  /healthcheck:
    get:
      tags:
        - developers
      summary: returns the health of the service
      operationId: healthCheck
      description: |
        The API endpoint handler performs various checks
        to ensure the service is operational.
      responses:
        '200':
          description: It works!
        '500':
          description: It's not working properly. Contact the administrator.
components:
  schemas:
    Account:
      type: object
      required:
        - id
        - login
        - creationDate
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: My Personal Account
        creationDate:
          type: string
          format: date-time
          example: '2022-06-29T13:37:00.001Z'
        lists:
          type: array
          items:
            $ref: '#/components/schemas/List'

          
    List:
      type: object
      required:
        - name
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        accountId:
          type: string
          example: ACME Corporation
        name:
          type: string
          example: My Task List
        creationDate:
          type: string
          format: date-time
          example: '2022-06-29T13:37:00.001Z'
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/Task'
    Task:
      type: object
      required:
        - name
        - description
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: Task0
        description:
          type: string
          example: Just do it !
        creationDate:
          type: string
          format: date-time
          example: '2022-06-29T13:37:00.001Z'
    ExtendedAccount:
      type: object
      required:
        - id
        - login
        - creationDate
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: My Personal Account
        creationDate:
          type: string
          format: date-time
          example: '2022-06-29T13:37:00.001Z'
        lists:
          type: array
          items:
            $ref: '#/components/schemas/ExtendedList'

          
    ExtendedList:
      type: object
      required:
        - name
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        accountId:
          type: string
          example: ACME Corporation
        name:
          type: string
          example: My Task List
        creationDate:
          type: string
          format: date-time
          example: '2022-06-29T13:37:00.001Z'
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/Task'